# The workflow uses the through semantic-release using .releaserc configuration 
# file which does the following:
# - runs commit analyzer and determines the type of release by analyzing commits
#   with conventional-changelog.
# - runs release notes generator which generates release notes for the commits 
#   added since the last release with conventional-changelog.
# - runs changelog which creates the CHANGELOG.md file with the release notes
#   generated
# - runs git/github to add a commit with the CHANGELOG.md file and tag version
#   with the following commit message chore(release): 0.0.0 [skip-ci]

name: release-tag-changelog-commit

on: 
  workflow_run:
    workflows: ["release-builds-tests"]
    types:
      - completed
  
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.8.0
      - run: npm ci
      - run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
